### ISSUE TITLE
Some mistakes in "Integrating Tailwind CSS in Blazor"

### ISSUE THREAD

**Issue by RonanBurkeGS** [timdeschryver/timdeschryver.dev#370]
Blog: https://timdeschryver.dev/blog/integrating-tailwind-css-in-blazor

Hey, I really liked this blog post but I've not been able to get things 100% working yet. Here are some issues I noticed:

1. This command is referred to: `npx tailwindcss -i ./Styles/tailwind.css -o ./wwwroot/styles.css` but then in the `App.blazor` file a different css file is referred to that isn't in the wwwroot? `<link rel="stylesheet" href="output.css" />`
2. The blog talks about using the `--watch` flag but the command shown afterwards doesn't have the `--watch` flag: `npx tailwindcss -i ./Styles/tailwind.css -o ./wwwroot/styles.css`
3. The "Optimizing the (CI) build" code snippet section doesn't include the watch command any more. The debug condition is also minifying the css (not just the release). The "EnvironmentVariables="NODE_ENV=production"" isn't clear and was giving me errors.

I'm not necessarily sure what is the correct answer to all of the above things. I wasn't able to get your methods working but they sound promising. Is there a final sample of the finished output available?

**Comment by timdeschryver** [comment]
Thanks for addressing this @RonanBurkeGS , I will revisit ASAP.

**Comment by timdeschryver** [comment]
Sorry it took this long, I hope you were able to fix these mistakes within your project.

It seems like I had two different versions, and I didn't update the snippets/texts accordingly.
Using your input I've updated article, and I also want to address your points here:
- You're right, I've mixed up `styles.css` and `output.css`. The new version only uses `styles.css`.
- The command now includes the `watch` flag
- This does indeed throws an error. The `EnvironmentVariables` needs be added to the `Exec` config instead of the `Target` config


Thanks again for your feedback, I really appreciate it!
